name: Sync to Azure DevOps

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repo
        uses: actions/checkout@v4

      - name: Push to Azure DevOps
        run: |
          git remote add azure-devops https://azuredevopsncpl@dev.azure.com/azuredevopsncpl/dockerapp/_git/dockerapp
          git push azure-devops main
